# Generated by Django 6.0.6 on 2026-07-06 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('ended', 'Ended')], default='lobby', max_length=20)),
                ('current_question_index', models.IntegerField(default=-1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_live_sessions', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
