# Generated by Django 6.0.6 on 2026-07-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_livesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
