# Generated by Django 6.0.6 on 2026-06-08 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_@]+$', 'Username can only contain letters, numbers, @, and _')]),
        ),
    ]
